# Generated by Django 3.2.3 on 2021-05-21 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0003_auto_20210521_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecomment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movieComments', to='accounts.user'),
            preserve_default=False,
        ),
    ]
