# Generated by Django 3.2.3 on 2021-05-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_article_movietitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='movieId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
