# Generated by Django 3.2.3 on 2021-05-25 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_article_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieComment',
        ),
    ]
