# Generated by Django 3.2.3 on 2021-05-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_delete_moviecomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='weather',
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.CharField(max_length=100),
        ),
    ]
